# Data sets for sandwich ingredients:
bread_list = [(1, "rye"),
			  (2, "white"),
			  (3, "wheat"),
			  (4, "cinnamon swirl"),
              (5, "pancakes"),
			  (6, "english muffin")]

main_list = [(1, "spam"),
			 (2, "turkey"),
			 (3, "potted meat"),
			 (4, "tofu"),
             (5, "chicken tenders"),
			 (6, "peanut butter"),
			 (7, "tuna"),
             (8, "roast beef"),
			 (9, "croghan bologna"),
			 (10, "smoked salmon")]

cheese_list = [(1, "cheddar"),
			   (2, "goat cheese"),
			   (3, "cream cheese"),
               (4, "smoked gouda"),
			   (5, "bleu cheese"),
			   (6, "easy cheese"),
               (7, "grated parmesean"),
			   (8, "pimento spread")]

roughage_list = [(1, "lettuce"),
				 (2, "cucumbers"),
				 (3, "pickled okra"),
                 (4, "tomatoes"),
				 (5, "apples"),
				 (6, "celery"),
                 (7, "bean sprouts"),
				 (8, "beets"),
				 (9, "pickles"),
                 (10, "mushy peas"),
				 (11, "banana"),
				 (12, "spicy peppers")]

wild_magic_list = [(1, "cinnamon sugar"),
				   (2, "garlic powder"),
                   (3, "sesame seeds"),
				   (4, "togarashi"),
				   (5, "furikake"),
                   (6, "salt & pepper"),
				   (7, "dill"),
				   (8, "gummy worms"),
                   (9, "tortilla chips"),
				   (10, "roasted seaweed"),
                   (11, "momofuku tingly salt"),
				   (12, "pizza seasoning"),
                   (13, "prunes"),
				   (14, "honey"),
				   (15, "cheetos"),
                   (16, "white pepper"),
				   (17, "ramen seasoning"),
                   (18, "curry powder"),
				   (19, "lemon squeeze"),
				   (20, "tajin")]

sauce_list = [(1, "ketchup"),
			  (2, "best foods mayo"),
			  (3, "kewpie mayo"),
              (4, "curry ketchup"),
			  (5, "yellow mustard"),
              (6, "stone ground mustard"),
			  (7, "horseradish mustard"),
              (8, "horsie sauce"),
			  (9, "momofuku chili crunch"),
              (10, "hummus"),
			  (11, "ranch dressing"),
			  (12, "italian dressing"),
              (13, "strawberry jam"),
			  (14, "apricot preserves"),
              (15, "sriracha"),
			  (16, "chipotle cholula"),
			  (17, "garlic aioli"),
              (18, "bbq sauce"),
			  (19, "pesto"),
			  (20, "marinara")]
